[[pages]]
path = "pages/home.py"
name = "InÃ­cio"
icon = "ğŸ "

[[pages]]
path = "pages/about.py"
name = "Sobre NÃ³s"
icon = "ğŸ“–"

[[pages]]
path = "pages/protein.py"
name = "Visualizar ProteÃ­na"
icon = "ğŸ§¬"

[[pages]]
path = "pages/aminoacids.py"
name = "Tabela de AminoÃ¡cidos"
icon = "ğŸ”¬"
